# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
