# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171031_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
