# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171102_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
