# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171126_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default='Select', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory'),
        ),
    ]
