# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171031_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
