# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:35
from __future__ import unicode_literals

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20171126_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory'),
        ),
    ]
