# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tracker_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='assignee',
            field=models.CharField(max_length=35),
        ),
    ]
